[build]
  base = ""
  publish = "public"
  command = """
    sed -i 's|\\[FIREBASE_API_KEY\\]|${FIREBASE_API_KEY}|g' public/index.html public/js/init.js
    sed -i 's|\\[FIREBASE_AUTH_DOMAIN\\]|${FIREBASE_AUTH_DOMAIN}|g' public/index.html public/js/init.js
    sed -i 's|\\[FIREBASE_PROJECT_ID\\]|${FIREBASE_PROJECT_ID}|g' public/index.html public/js/init.js
    sed -i 's|\\[FIREBASE_STORAGE_BUCKET\\]|${FIREBASE_STORAGE_BUCKET}|g' public/index.html public/js/init.js
    sed -i 's|\\[FIREBASE_MESSAGING_SENDER_ID\\]|${FIREBASE_MESSAGING_SENDER_ID}|g' public/index.html public/js/init.js
    sed -i 's|\\[FIREBASE_APP_ID\\]|${FIREBASE_APP_ID}|g' public/index.html public/js/init.js
    sed -i 's|\\[FIREBASE_MEASUREMENT_ID\\]|${FIREBASE_MEASUREMENT_ID}|g' public/index.html public/js/init.js
    sed -i 's|\\[STRIPE_PUBLIC_KEY\\]|${STRIPE_PUBLIC_KEY}|g' public/index.html public/js/init.js
  """

[build.environment]
  STRIPE_PUBLIC_KEY = "pk_test_51RBeP6B311TbF66104ceu6MjOAU7FBEHtNyrCccF93ZJNgj4QGQPirUo28iyaWewu6xX9frkQrEwCR2kVdQb5XrC00aNVEvPJ5"
  FIREBASE_API_KEY = "AIzaSyCrSN8xc3KTGrc2gUzcqerL6SSYrF3LXZM"
  FIREBASE_AUTH_DOMAIN = "fieldcommand.firebaseapp.com"
  FIREBASE_PROJECT_ID = "fieldcommand"
  FIREBASE_STORAGE_BUCKET = "fieldcommand.firebasestorage.app"
  FIREBASE_MESSAGING_SENDER_ID = "944064034218"
  FIREBASE_APP_ID = "1:944064034218:web:bb6744acdd0d66e9ba27d3"
  FIREBASE_MEASUREMENT_ID = "G-C3TQ7DWTX8"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "connect-src 'self' https://us20.list-manage.com https://firestore.googleapis.com https://www.google-analytics.com https://identitytoolkit.googleapis.com https://securetoken.googleapis.com"